# Generated by Django 4.1.3 on 2022-11-15 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField(default=None, null=True)),
                ('registration_deadline', models.DateTimeField(default=None, null=True)),
                ('pictures', models.FileField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 21, 58, 48, 355613))),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
