# Generated by Django 4.1.3 on 2022-11-16 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 14, 31, 5, 317042)),
        ),
        migrations.AlterField(
            model_name='project',
            name='pictures',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
