# Generated by Django 4.1.3 on 2022-11-16 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_created_date_alter_project_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 15, 21, 17, 706521)),
        ),
    ]
